apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

data:
  mapRoles: |
    - rolearn: arn:aws:iam::390635731868:role/eksctl-brain-tasks-cluster-nodegroup-NodeInstanceRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::390635731868:role/service-role/codebuild-BrainTask-build-app-service-role
      username: codebuild
      groups:
        - system:masters
